export const USER_REGISTER_LOADING = 'USER_REGISTER_LOADING';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const FETCH_BLOGS_LOADING = 'FETCH_BLOGS_LOADING';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_ERROR = 'FETCH_BLOGS_ERROR';

export const FETCH_BLOG_LOADING = 'FETCH_BLOG_LOADING';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_ERROR = 'FETCH_BLOG_ERROR';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const ADD_TO_SAVED = 'ADD_TO_SAVED';
export const DELETE_FROM_SAVED = 'DELETE_FROM_SAVED';

export const GET_COMMENTS = 'GET_COMMENTS';

export const SORT_BY_ALPHABET = 'SORT_BY_ALPHABET';